{{- if .Values.wordpress.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress.fullname" . }}
  annotations:
    {{- toYaml .Values.wordpress.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.wordpress.ingress.hosts | first }}
      http:
        paths:
          - path: {{ .Values.wordpress.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "wordpress.fullname" . }}
                port:
                  name: http
{{- end }}